### ISSUE TITLE
Make refresh rate of sensor values configurable

### ISSUE THREAD

**Issue by thedoginthewok** [MTrab/landroid_cloud#11]
The landroid app has a refresh function.   
It would be nice to be able to set a value in the home assistant config file that changes the refresh rate of the sensor values.

**Comment by MTrab** [comment]
I'm setting won't fix label, as the plan is to subscribe to the push function of the landroid, in a later version.
Then all information is the current at any time.

**Comment by thedoginthewok** [comment]
That would be perfect!

**Comment by GSzabados** [comment]
> I'm setting won't fix label, as the plan is to subscribe to the push function of the landroid, in a later version.
> Then all information is the current at any time.

I just wanted to ask what is the current refresh rate, as my mower just finished mowing, returned home and charging now, but the status still shows a value from a hour or so ago, when the mower started the work. (Battery updated 18 minutes ago, when it was at 15%.)

Has the subscription been implemented and is it broken, or just the refreshing is broken for some reason?

Actually the log shows from more than an hour ago this, but I believe that was due to the state when the mower was moved from the garage to the garden and turned on.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 146, in _forward_on_message
    self._decodeData(json_message)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 186, in _decodeData
    self.gps_latitude = data['dat']['modules']['4G']['gps']['coo'][0]
KeyError: 'gps'
```

**Comment by MTrab** [comment]
What version of the plugin are you using? That error look similar to an old error which are fixed.

**Comment by GSzabados** [comment]
> What version of the plugin are you using? That error look similar to an old error which are fixed.

Yes, I know, it looks quite similar to the one what was fixed during the winter hibernation period. I just can guess, that the mower has all the other parameters, but not a GPS fix.

I crosschecked, I have 1.6.5 written in the manifest, so I believe that is the latest, disregarding the fact, that the release bage has 1.6.6 written there.
(I believe you have added the 1.6.5 to the manifest recently to comply with HA's version number requirements.)

I still don't see how the status is updated, it has received the status about 15 minutes later, then I posted the question. Seems to be a bit out of sync...

(My nower uses the Find My Landroid module, but the status was updated a few times in the native Landroid app meanwhile. )

**Comment by johny-mnemonic** [comment]
@MTrab Any update on that push subscription?
My Landroid is getting old and it's battery is weaker, so I am trying to send it home sooner by HA automation. It would be useful to have current battery state in HA. Now the update interval seems long and random.

**Comment by GSzabados** [comment]
> Now the update interval seems long and random.

Do you use a Find My Landroid module? That sends reports absolutely randomly. It is impossible to predict that.

**Comment by MTrab** [comment]
Unfortunately, if we set the refresh polling any lower, you'll risk getting banned from your account.

**Comment by johny-mnemonic** [comment]
@MTrab yeah, I expected something like that. That's why I asked about the push subscription status.

If push subscription is not on the horizon, another way would be to make the polling rate dynamically configurable from HA. 
With that it would be for example possible to set it to low rate when the mower finishes it's scheduled job and to high rate during mowing.
As the mowing is usually just a few hours a day at max, we could achieve better monitoring during mowing while still not risking to get banned from the Worx API.

What do you think?

**Comment by MTrab** [comment]
Push should already work - if you go in the app and force a sync from there, the data would update in HA as well

**Comment by johny-mnemonic** [comment]
@MTrab oh, I see. I thought, that push means it will update with every new event on the API, not that you will have to manually trigger it.
Is there a way to trigger that sync from HA then?

**Comment by MTrab** [comment]
It will update whenever the droid sends data back to the cloud - the way I mentioned was just to trigger an update from the app.
No current way of doing this from HA, as we need to have some rate-limiting in mind for this.

**Comment by johny-mnemonic** [comment]
@MTrab OK, got it. That explains why it is so random.
I understand the issue with the need of having some rate-limit, that's why I suggested to use dynamic polling interval. That should improve the frequency of data updates and don't rely on the unreliable syncs triggered by Android app. All while keeping the overall number of API calls reasonable low.
BTW: Do you have an idea of what the limit approximately is?
