### ISSUE TITLE
no devices in HA

### ISSUE THREAD

**Issue by RoSulek1** [MTrab/landroid_cloud#6]
After adding integration i see only sensors of my Landroid.
Commands start/stop/home is possible only via service, then i cannot see the device Landroid in Devices.
Sychro with Google is inpossible. Voice command (OK Google, Start Landroid) is impossible

**Comment by MTrab** [comment]
That is correct - you need to make your own scenes for this to work as there is no mower controls in Home Assistant.

**Comment by dac21** [comment]
I also would love to have a entity.  I have a robotic vacuum using the custom vacuum card.  The functions are basically the same as our mowers.  I seems to be that error, battery level should be attributes of the entity and the status should be the state.  This would make it similar to other items in HA.

**Comment by MTrab** [comment]
There are no mower controls, as this have not been designed in Home Assistant at the moment, so it's hard to decide how to present the data.
As long as there are no mower domain I thing I'll keep it as it is.

**Comment by RoSulek1** [comment]
Wrong.

I have old roomba (660) without wifi.
After add an esp module and set it as entity i can add it to HA as simple
switch.

What the matter to set entity landroid as simple switch, and after that i
can sync it with GH.
Just say - Hey, google turn on... Landroid.

Last interace on witch U based was representative as entity and simple
switch.

sob., 9 maj 2020, 21:19 użytkownik Morten Trab <notifications@github.com>
napisał:

**Comment by MTrab** [comment]
But that's no a device - that's a switch, that's a whole other story.
A switch for starting / stopping I might add.
A device I don't think will happen until HA devs. add mower controls natively.

**Comment by dac21** [comment]
Thanks, I have a feature request to add the mower controls. Sent from Mail for Windows 10 From: Morten TrabSent: Saturday, May 9, 2020 3:46 PMTo: MTrab/landroid_cloudCc: dac21; CommentSubject: Re: [MTrab/landroid_cloud] no devices in HA (#6) But that's no a device - that's a switch, that's a whole other story.A switch for starting / stopping I might add.A device I don't think will happen until HA devs. add mower controls natively.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Barma-lej** [comment]
For Landroid voice control with Google Home:
1. You can add Landroid to Google Home. This is native Worx support.
2. You can also use [halandroid package](https://github.com/Barma-lej/halandroid)
