### ISSUE TITLE
can not send the landroid configuration from HA after some hours or days

### ISSUE THREAD

**Issue by lukashaensel** [MTrab/landroid_cloud#61]
Hey!
there is a problem sending data from HA to Landroid. I use the attribute "timeextension" to switch the mower. I start the schedule by setting the "timeextension" to 100 and stop the schedule by setting the "timeextension" to -100. This works very well for me until the problem occurs.

After some time (hours or days) HA does not send the new configuration with the time extension. I don't know why. The Landroid app is working fine. To fix the problem I have to restart the HA server. 

My problem: I don't know what exactly the problem is. I can't find any entry in the HA log file. Is there any way to enable a debug mode so I can give you more infos about the error?

Thanks a lot

**Comment by MTrab** [comment]
I have no idea why you experience this - haven't experienced it myself, neither heard of this before.

**Comment by GSzabados** [comment]
> I have no idea why you experience this - haven't experienced it myself, neither heard of this before.

I have a similar issue by starting the Lawnmower. It does not react to any commands, but once I restart HA it starts to work again.

Messages from the mower coming in without any issue, only commands are not executed. 

Wouldn't be the case that a token hasn't been refreshed after some time and it is just failing to execute? Just a random guess. Seen similar issues with expired tokens in other integrations.

Otherwise no error in the log. I've just turned on debug as well to see where things go wrong.

**Comment by MTrab** [comment]
If it were at problem with the token (which are refreshed when needed), then I would assume alot mere "noise" around this issue - and then I'd see it myself

**Comment by GSzabados** [comment]
> If it were at problem with the token (which are refreshed when needed), then I would assume alot mere "noise" around this issue - and then I'd see it myself

I truly understand you, but I have no other idea what could cause this.

I started to use the controls from HA recently, so I don't have any further experience. But there isn't any error or warning in the log regarding why it is not starting the mower or sending it home.

Otherwise the reason why I think that it must be the token, because I have some issues with the Landroid app as well.
Once it was opened before and just pulled back to screen on Android, it is unable to show any details about the mower. It has to be closed fully and re-opened, so it loads from "scratch". That seems to be a token refresh issue as well for me.

Here is reddit topic about what I mean:

https://www.reddit.com/r/worxlandroid/comments/oyczgk/i_have_to_close_and_restart_the_app_every_time/

Would be possible to force the integration to refresh the token without restarting HA?

**Comment by lukashaensel** [comment]
Hello community,
it's nice to hear that I'm not alone with the problem.
As far as I can still remember, the debug mode didn't help me either.
I couldn't solve the problem either, so I switched to https://github.com/virtualzone/landroid-bridge.  I connected this to the Home Assistant via mqtt and http.

I don't know how you installed your Home Assistant.  For me it is a Proxmox server cluster with an HA Ubuntu VM which has shared storage.  Do you happen to have a similar structure?  From what I heard, Docker has quite a few problems with shared storage and lxc containers (or vice versa).  But I'm absolutely not a professional there.

Your problem with the app.  It looks to me like I've had the problem before.  I had called the support at the time.  At first they were also at a loss.  Later I was supposed to sign off all devices that were connected to the Landroid account for one night from the account.  In my case, switch off the mower, log off the apps and also log off or switch off the Home Assistant.  Maybe it will help you.

Good luck and best regards
 Lukas

**Comment by GSzabados** [comment]
> I don't know how you installed your Home Assistant. For me it is a Proxmox server cluster with an HA Ubuntu VM which has shared storage. Do you happen to have a similar structure? From what I heard, Docker has quite a few problems with shared storage and lxc containers (or vice versa). But I'm absolutely not a professional there.

@lukashaensel - No, nothing like that. It is a Debian Supervised installation. 

@MTrab - Weird enough, since I enabled debug logging and restarted HA, I don't have any issue so far. But meanwhile the Landroid app has been updated as well, and it says that it has been completely rewritten. So might be a mix of both...
I will get back if I see the issue again and I can see anything in the log. Sorry to bother...
