### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Bouni** [MTrab/landroid_cloud#90]
## Configuration

```yaml

landroid_cloud:
  - email: !secret worx_email 
    password: !secret worx_pw

```

## Describe the bug

The integration seems to be working (my mower is outside and ready to use but I don't use it at the moment due to winter 😉 )
But I see repeating errors in my logs.

## Debug log

```text

2022-01-14 12:02:09 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/landroid_cloud/__init__.py", line 391, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 158, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 163, in _decodeData
    data = json.loads(indata)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Th3M1k3y** [comment]
I just got the same error after restarting HA.

**Comment by mk-maddin** [comment]
Same here ..since around update to 2021.12.10 I would say

**Comment by MTrab** [comment]
Have you tried updating to latest release of this integration?

**Comment by mk-maddin** [comment]
Just verified by reinstalling the custom component.
Unfortunately just had the error again (but with different line number as 391 is commented out in latest version).
It seems to me the issue appears if no reply comes from landroid (maybe because landroid is offline? - mine is because its winter :P )

`2022-01-21 13:36:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/landroid_cloud/__init__.py", line 396, in async_force_update
await self._hass.async_add_executor_job(self._client.getStatus)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 158, in getStatus
self._decodeData(status)
File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 163, in _decodeData
data = json.loads(indata)
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Th3M1k3y** [comment]
> Have you tried updating to latest release of this integration?

I am now on 1.8.1 and the error at start up has gone away. :)

**Comment by mk-maddin** [comment]
@Th3M1k3y : To be truth I do not think you have seen the exact same issue, but instead the one I described here:
https://github.com/MTrab/landroid_cloud/pull/89#issue-1091520976

**Comment by rothnic** [comment]
I have been having this issue as well. I'm on 1.8.1 using HA 2021.12.8. Since the last restart, it says this error has occurred ~250 times.

![image](https://user-images.githubusercontent.com/452052/152655935-92df2fe9-1814-413d-9352-08245c12c381.png)

**Comment by HenrikBurton** [comment]
I have a fresh installation and get the same result on 1.8.1. My mover are in the garage waiting for the spring to arive.

**Comment by odechr** [comment]
I have the same issue. Now on version 2022.01.05

**Comment by MTrab** [comment]
Could you please report which models you have?
My old S500 doesn't produce this error, even when turned off (and have been so for at few months)

**Comment by HenrikBurton** [comment]
I have a WR165E on firmware 3.26.

**Comment by mk-maddin** [comment]
Running a WR105SI.1 - Firmware 3.52

**Comment by Remko76** [comment]
I also have the same issue. I have a WR500SI.1, firmware 3.52.

My mower is up and running again, the integration works, I can start and stop it,  get all the info but this error keeps appearing in the log.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/landroid_cloud/__init__.py:396 
Integration: Worx Landroid Cloud (documentation, issues) 
First occurred: February 25, 2022, 9:21:37 PM (24 occurrences) 
Last logged: 8:51:37 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/landroid_cloud/__init__.py", line 396, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 158, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 163, in _decodeData
    data = json.loads(indata)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MTrab** [comment]
Very strange - what version of the integration are you running?
And could you perhaps try reinstalling the integration?

**Comment by Remko76** [comment]
I am running version 1.8.1 off the integration. I just now reinstalled it and will let you know if this makes any difference.

**Comment by Remko76** [comment]
I reinstalled the integration, using the latest 1.8.1 version, but I still keep getting the above mentioned error.

**Comment by rothnic** [comment]
I was able to reproduce the issue by cloning the current pyworxcloud git repo, then modifying the Example/example.py file to loop forever, then call the getStatus() method every 10 seconds. After 30min-1hr I ended up seeing the same error.

I added a try/except statement in there to catch the exception next time, so hopefully I can track down a bit more what is going on. 

The exception that it prints out seems to suggest that somehow `None` is getting passed into [_decodeData](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L158), which `json.loads` isn't appreciating. I don't see how it is possible for that to happen off-hand. The API's get_status method is called [here](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L154), which is implemented [here](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/worxlandroidapi.py#L93),  which ultimately hits the [_call](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/worxlandroidapi.py#L98) method.

I was thinking this might be a random timeout issue that could occur for those where the mower is close to the limit of the range. It appears that in one way or another, the `_call` method would return either [False](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/worxlandroidapi.py#L112) or [json](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/worxlandroidapi.py#L114) data, rather than `None`.

Then, whether or not there is JSON data or `False` returned, here the module [converts it back to a string](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L155). So, I can't seem to see where the `None` comes from. I'll respond again when I get this to fail one more time and can hopefully inspect things upstream a bit better.

**Comment by MTrab** [comment]
@rothnic gald you can help - can't reproduce the error, even with the mower switched off - BUT! Be aware, that calling the getStatus that often will most likely result in banning your account.

**Comment by rothnic** [comment]
What is safe? I see there is a 30s limit built into the library.

**Comment by MTrab** [comment]
I'm not perfectly sure about the safe limit, hence I'm trying to throttle the requests to a 30s minimum

**Comment by rothnic** [comment]
I'll back that off a bit and hope it happens again.

I do think that if you could [wrap this decode call](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L163) with a try/except we could at least avoid the exception and you could add a logger call with a warning with any details you have available.

**Comment by MTrab** [comment]
That sound like a good starting point :)

**Comment by rothnic** [comment]
Actually, I do know at least that the reason `False` was returned from the `_call` method of WorxLandroidAPI is because a timeout occurred. I noticed that the exception message was "Timeout connecting", which means it reached [this line](https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/worxlandroidapi.py#L111). So yeah, anything retrieving data from this method needs to be able to handle that situation.

This being just a timeout would explain why everything seems to be generally working fine while our logs are filled with these exceptions.

**Comment by MTrab** [comment]
That would also explain why not everyone see this error.
Might see of I can do some catching of the timeout exception, and then return a JSON value representing an timeout error.

Just need to reset my test env, as it went completely bonkers yesterday :D
Think I might need to setup a seperate one for this even, as I'm working on a complete rebuild of the integration, to make it compatible with integration flow :)

**Comment by MTrab** [comment]
Something is really off in my dev-env.
Just getting ```object bool can't be used in 'await' expression``` in the initialize section when running the example.
It used to work just fine :/

**Comment by rothnic** [comment]
> Something is really off in my dev-env. Just getting `object bool can't be used in 'await' expression` in the initialize section when running the example. It used to work just fine :/

I forgot I had this same issue. I think I noticed that the initialize method was recently converted to be a synchronous function, rather than asynchronous. You just have to remove the await on the initialize call.

**Comment by MTrab** [comment]
DOH! I must be getting old :D Thanks

**Comment by MTrab** [comment]
@rothnic could you try latest source for pyworxcloud?
I have added better error handling which should prevent a return of type bool on errors

**Comment by rothnic** [comment]
I have it running, so will try to provide an update this weekend. From a quick glance at the code, it appears like it should handle the error cases without issue now

**Comment by MTrab** [comment]
I've had it running in my Home Assistant during the weekend, and I can see some random authentication errors, with the latest lib.
Haven't noticed that before, althou they are handled now. And haven't seen the original issue (hadn't seen it before either).
So how was your test, @rothnic ?

**Comment by rothnic** [comment]
I noticed some odd authentication errors as well, but overall seems to work. I agree that at least these timeouts or auth errors or whatever is randomly appearing are being handled now.

**Comment by MTrab** [comment]
Just pushed a new release to the integration with the new error handling.
This should fix the issues seen here with better error handling - althou it doesn't fix the reason behind the errors (which seems like Landroid Cloud issues, but not 100% sure)

**Comment by Remko76** [comment]
Thanks for looking into this. I updated right away and will report if I see the error again. I am also sure there is no problem in functionality, just annoying messages which should be gone now... Thanks again!!

**Comment by Remko76** [comment]
I don't the error anymore, but it was replaced with an "unauthorized" error:

```
Logger: pyworxcloud.worxlandroidapi
Source: /usr/local/lib/python3.9/site-packages/pyworxcloud/worxlandroidapi.py:121 
First occurred: March 7, 2022, 9:53:19 PM (19 occurrences) 
Last logged: 6:53:19 AM

Error: Unauthorized
```

**Comment by MTrab** [comment]
Yup - that was exactly what we saw in the tests too.
I think it's actually some timeout in the auth. process and I'll look more into this and see if I can make it even prettier ;) At least we don't have those ugly stack trace errors anymore :)
